services:
  mongo:
    image: mongo:latest
    container_name: mongo-network-test
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 8000:27017
    networks:
      - backend-network

  backend:
    build: ./backend
    container_name: backend-network-test
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
